version: '3'
services:
  drivent-production:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drivent-back
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    working_dir: /usr/src/drivent
    command: bash -c "npx prisma migrate dev && npx prisma db seed && npm run start"
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - "drivent-postgres-production"
      - "drivent-redis-production"
  drivent-postgres-production:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /usr/local/drivent-pg/data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
  drivent-redis-production:
    image: 'redis'
    restart: always
    ports: 
      - 6380:6379
    command: redis-server
    volumes: 
      - drivent-redis-production:/data
  drivent-nginx:
    image: nginx
    ports:
      - 3001:80
    depends_on:
      - drivent-production
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /usr/src/drivent/front-end:/var/www/html
volumes:
  drivent-postgres-production:
    driver: local
  drivent-redis-production:
    driver: local